import styles from './page.module.scss'
import Image from 'next/image'
import logo from './../images/logo.svg'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={styles.MainLayout}>
        <div className={styles.ContentWrap}>
            <video className={styles.bg_video} width="100%" autoPlay muted loop>
                <source src={require('./../images/bg.mp4')} type="video/mp4" />
            </video>

            <div className={styles.content}>
                <header className={styles.Appheader}>

                    {/* <img src={logo} className="App-logo" alt="logo" /> */}
                    <Image
                      src={logo}
                      alt="Logo"
                      // width={500} automatically provided
                      // height={500} automatically provided
                      // blurDataURL="data:..." automatically provided
                      // placeholder="blur" // Optional blur-up while loading
                    />
                    <div className={styles.Navbutton}
                    //  onClick={()=>{showNavbar()}}
                      >
                        {/* <Button>
                            <FontAwesomeIcon icon={faBars} />
                        </Button> */}
                    </div>
                </header>
                {/* <Login/> */}
                {children}
                {/* {props.children} */}
            </div>
        </div>

        {/* <Navbar active={[buttonState, setbuttonState]} myClass="Navbar" /> */}
    </div>
   
  )
}
